import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { initializeDatabase } from './db.js';
import { listRaces, getHistory, recordObservation, getStorage, getConfig, refresh, getRuns, getArchiveFacets } from './controllers/electionController.js';
await initializeDatabase();
const app=express(); app.use(express.json());
app.get('/api/health',(_,res)=>res.json({status:'ok'}));
app.get('/api/races',listRaces); app.get('/api/races/:id/history',getHistory); app.post('/api/races/:id/observations',recordObservation);
app.get('/api/config',getConfig); app.get('/api/storage',getStorage); app.get('/api/ingest-runs',getRuns); app.post('/api/refresh',refresh);
app.get('/api/archive/facets',getArchiveFacets);
app.use((error,req,res,next)=>res.status(error.status||500).json({error:error.message||'Internal server error'}));
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'); app.use(express.static(path.join(root,'dist'))); app.get('*splat',(req,res)=>res.sendFile(path.join(root,'dist','index.html')));
app.listen(process.env.PORT||3000,()=>console.log('Signal API listening on http://localhost:3000'));
